name: Test
on:
  workflow_dispatch:
  schedule:
  - cron: "0/5 * * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: "3.10"
    - run: pip install requests
    - run: python test.py
