name: test_undetected_chromedriver.py
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test_undetected_chromedriver.yml'
      - 'test_undetected_chromedriver.py'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: sudo chmod 777 $CHROMEWEBDRIVER/chromedriver
      - run: pip install undetected-chromedriver
      - run: xvfb-run --auto-servernum python test_undetected_chromedriver.py
