name: test_undetected_chromedriver.py
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: "3.10"
    - uses: browser-actions/setup-chrome@v0.0.0
    - run: yum install Xvfb
    - run: pip install requests beautifulsoup4 undetected-chromedriver
    - run: xvfb-run python test_undetected_chromedriver.py
