name: test1.py
on:
  workflow_dispatch:
  push:
    paths:
      - 'test1.py'
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python test1.py
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
