name: test_undetected_chromedriver.py
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@latest
    - uses: actions/setup-python@v4
      with:
          python-version: "3.10"
    - run: pip install beautifulsoup4 undetected-chromedriver selenium-stealth
    - uses: hankolsen/xvfb-action@master
      with:
        run: python test_undetected_chromedriver.py
